name: demo workflow
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output the message event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
