name: demo workflow
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Output the message to start tests
        run: echo "Start tests"
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: List files after build
        run: ls -la
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-files
          path: .next
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Output the message event data
        run: echo "some message"
